use_frameworks!

platform :ios, '11.0'

target 'WatchDogMainThread_Example' do
  pod 'WatchDogMainThread', :path => '../'

  target 'WatchDogMainThread_Tests' do
    inherit! :search_paths

    
  end
end
